/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlthisathach;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class QuestionPanel extends javax.swing.JPanel {

    /**
     * Creates new form CauHoi
     */
    public QuestionPanel() {
        initComponents();
        table_update();
        FillcomboLbl();
    }
    Connection con = null;
    PreparedStatement pstmt = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement query;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCauHoi = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCauHoi = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDapAn1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDapAn2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDapAn3 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDapAn4 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbbLbl = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDapAn5 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtID = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        tableCauHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Loại bằng lái", "Tên câu hỏi", "Đáp án 1", "Đáp án 2", "Đáp án 3", "Đáp án 4", "Đáp án Đúng"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    tableCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tableCauHoiMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tableCauHoi);

    txtCauHoi.setColumns(20);
    txtCauHoi.setRows(5);
    jScrollPane2.setViewportView(txtCauHoi);

    jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel1.setText("Câu hỏi");

    jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel2.setText("Đáp án 1");

    txtDapAn1.setColumns(20);
    txtDapAn1.setRows(5);
    jScrollPane3.setViewportView(txtDapAn1);

    txtDapAn2.setColumns(20);
    txtDapAn2.setRows(5);
    jScrollPane4.setViewportView(txtDapAn2);

    jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel3.setText("Đáp án 2");

    txtDapAn3.setColumns(20);
    txtDapAn3.setRows(5);
    jScrollPane5.setViewportView(txtDapAn3);

    jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel4.setText("Đáp án 3");

    txtDapAn4.setColumns(20);
    txtDapAn4.setRows(5);
    jScrollPane6.setViewportView(txtDapAn4);

    jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel5.setText("Đáp án 4");

    jButton1.setText("Thêm");
    jButton1.setMaximumSize(new java.awt.Dimension(81, 23));
    jButton1.setMinimumSize(new java.awt.Dimension(81, 23));
    jButton1.setPreferredSize(new java.awt.Dimension(81, 23));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setText("Chỉnh sửa");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jButton3.setText("Xóa");
    jButton3.setMaximumSize(new java.awt.Dimension(81, 23));
    jButton3.setMinimumSize(new java.awt.Dimension(81, 23));
    jButton3.setPreferredSize(new java.awt.Dimension(81, 23));
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel18.setText("Loại bằng lái:");

    txtDapAn5.setColumns(20);
    txtDapAn5.setRows(5);
    jScrollPane7.setViewportView(txtDapAn5);

    jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel6.setText("Đáp án đúng");

    jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel7.setText("ID:");

    txtID.setColumns(20);
    txtID.setRows(5);
    jScrollPane8.setViewportView(txtID);

    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlthisathach/icons/Actions-document-edit-icon-48.png"))); // NOI18N

    jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
    jLabel9.setText("Quản lý câu hỏi thi bằng lái xe");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(14, 14, 14)
                    .addComponent(jScrollPane2))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel18)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(cbbLbl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane4))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane5))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane6))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane7))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(388, 388, 388)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel9)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel8)
                .addComponent(jLabel9))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18)
                .addComponent(cbbLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
            query = con.prepareStatement("INSERT INTO cauhoi (lbl_id,ten_cau_hoi,dap_an_1,dap_an_2,dap_an_3,dap_an_4, dap_an_dung) VALUES(?,?,?,?,?,?,?)");
            
            Integer A1 = 1;
            Integer A2 = 2;
            Integer A3 = 3;
            Integer A4 = 4;
            Integer B1 = 5;
            Integer B2 = 6;
            Integer C = 7;
            Integer D = 8;
            Integer E = 9;
            Integer F = 10;
            Integer FB2 = 11;
            Integer FC = 12;
            Integer FD = 13;
            Integer FE = 14;
            Object selectedItem = cbbLbl.getSelectedItem();
            String selectedItemStr = selectedItem.toString();
            if (selectedItemStr.equals("Hạng A1")) {
                query.setInt(1,A1);
            }
            if (selectedItemStr.equals("Hạng A2")) {
                query.setInt(1,A2);
            }
            if (selectedItemStr.equals("Hạng A3")) {
                query.setInt(1,A3);
            }
            if (selectedItemStr.equals("Hạng A4")) {
                query.setInt(1,A4);
            }
            if (selectedItemStr.equals("Hạng B1")) {
                query.setInt(1,B1);
            }
            if (selectedItemStr.equals("Hạng B2")) {
                query.setInt(1,B2);
            }
            if (selectedItemStr.equals("Hạng C")) {
                query.setInt(1,C);
            }
            if (selectedItemStr.equals("Hạng D")) {
                query.setInt(1,D);
            }
            if (selectedItemStr.equals("Hạng E")) {
                query.setInt(1,E);
            }
            if (selectedItemStr.equals("Hạng F")) {
                query.setInt(1,F);
            }
            if (selectedItemStr.equals("Hạng FB2")) {
                query.setInt(1,FB2);
            }
            if (selectedItemStr.equals("Hạng FC")) {
                query.setInt(1,FC);
            }
            if (selectedItemStr.equals("Hạng FD")) {
                query.setInt(1,FD);
            }
            if (selectedItemStr.equals("Hạng FE")) {
                query.setInt(1,FE);
            }
            query.setString(2,txtCauHoi.getText());
            query.setString(3,txtDapAn1.getText());
            query.setString(4,txtDapAn2.getText());
            query.setString(5,txtDapAn3.getText());
            query.setString(6,txtDapAn4.getText());
            query.setString(7,txtDapAn5.getText());
            query.executeUpdate();   
            table_update();
            JOptionPane.showMessageDialog(null,"Thêm thành công!");
            txtCauHoi.setText("");
            txtDapAn1.setText("");
            txtDapAn2.setText("");
            txtDapAn3.setText("");
            txtDapAn4.setText("");
            txtDapAn5.setText("");
            txtID.setText("");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String cau_hoi = txtCauHoi.getText();
            String DA1 = txtDapAn1.getText();
            String DA2 = txtDapAn2.getText();
            String DA3 = txtDapAn3.getText();
            String DA4 = txtDapAn4.getText();
            String DA5 = txtDapAn5.getText();
            String idx = txtID.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
            query = con.prepareStatement("update cauhoi set ten_cau_hoi=?, dap_an_1=?, dap_an_2=?, dap_an_3=?,dap_an_4=?, dap_an_dung=? where id_cau_hoi=? ");
            query.setString(1, cau_hoi);
            query.setString(2, DA1);
            query.setString(3, DA2);
            query.setString(4, DA3);
            query.setString(5, DA4);
            query.setString(6, DA5);      
            query.setString(7, idx);
            query.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cập nhập thành công!");
            table_update();
            txtCauHoi.setText("");
            txtDapAn1.setText("");
            txtDapAn2.setText("");
            txtDapAn3.setText("");
            txtDapAn4.setText("");
            txtDapAn5.setText("");
            txtID.setText("");
            txtCauHoi.requestFocus();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String ch = txtID.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
            query = conn.prepareStatement("delete from cauhoi where id_cau_hoi=?");
            query.setString(1, ch);
            query.executeUpdate();
            JOptionPane.showMessageDialog(this, "Đã xóa!");
            table_update();
            txtCauHoi.setText("");
            txtDapAn1.setText("");
            txtDapAn2.setText("");
            txtDapAn3.setText("");
            txtDapAn4.setText("");
            txtDapAn5.setText("");
            txtID.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCauHoiMouseClicked
        DefaultTableModel df = (DefaultTableModel)tableCauHoi.getModel();
        int selectedIndex = tableCauHoi.getSelectedRow();        
        txtCauHoi.setText(df.getValueAt(selectedIndex, 2).toString());
        txtDapAn1.setText(df.getValueAt(selectedIndex, 3).toString());
        txtDapAn2.setText(df.getValueAt(selectedIndex, 4).toString());
        txtDapAn3.setText(df.getValueAt(selectedIndex, 5).toString());
        txtDapAn4.setText(df.getValueAt(selectedIndex, 6).toString());
        txtDapAn5.setText(df.getValueAt(selectedIndex, 7).toString());
        txtID.setText(df.getValueAt(selectedIndex, 0).toString());
    }//GEN-LAST:event_tableCauHoiMouseClicked

    
    
    private void table_update(){
        int c;
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
                query = conn.prepareStatement("SELECT * FROM cauhoi");
                ResultSet rs = query.executeQuery();
                ResultSetMetaData rss = rs.getMetaData();
                c = rss.getColumnCount();
                
                DefaultTableModel df = (DefaultTableModel)tableCauHoi.getModel();
                df.setRowCount(0);
                    while(rs.next()){
                        Vector v2 = new Vector();
                        for (int a = 1; a <=c; a++) {
                            v2.add(rs.getString("id_cau_hoi"));
                            v2.add(rs.getString("lbl_id"));
                            v2.add(rs.getString("ten_cau_hoi"));
                            v2.add(rs.getString("dap_an_1"));
                            v2.add(rs.getString("dap_an_2"));
                            v2.add(rs.getString("dap_an_3"));                 
                            v2.add(rs.getString("dap_an_4"));
                            v2.add(rs.getString("dap_an_dung"));
                        }
                        df.addRow(v2);
                    }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
    }
    private void FillcomboLbl(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
            query = conn.prepareStatement("SELECT * FROM loaibanglai");
            rs=query.executeQuery();
            while(rs.next()){
                String name = rs.getString("ten_loai_bang_lai");
                cbbLbl.addItem(name);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tableCauHoi;
    private javax.swing.JTextArea txtCauHoi;
    private javax.swing.JTextArea txtDapAn1;
    private javax.swing.JTextArea txtDapAn2;
    private javax.swing.JTextArea txtDapAn3;
    private javax.swing.JTextArea txtDapAn4;
    private javax.swing.JTextArea txtDapAn5;
    private javax.swing.JTextArea txtID;
    // End of variables declaration//GEN-END:variables
}
