/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlthisathach;

import mysql_DTO.UsersDTO;
import mysql_DAO.UsersDAO;


import java.awt.Color;
import java.io.File;
import java.math.BigInteger;
import java.sql.PreparedStatement;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author DELL
 */
public class StaffPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form StaffPanel
     */
    public StaffPanel() {
        initComponents();
        table_update();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNameStaff = new javax.swing.JTextField();
        txtMailStaff = new javax.swing.JTextField();
        txtNumberStaff = new javax.swing.JTextField();
        rdbMale = new javax.swing.JRadioButton();
        rdbFemale = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddressStaff = new javax.swing.JTextArea();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbbChucVu = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jLabel10.setText("Họ tên:");

        jLabel11.setText("Email:");

        jLabel12.setText("Số điện thoại:");

        jLabel13.setText("Giới tính:");

        jLabel14.setText("Địa chỉ:");

        buttonGroup1.add(rdbMale);
        rdbMale.setText("Nam");
        rdbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbFemale);
        rdbFemale.setText("Nữ");

        txtAddressStaff.setColumns(20);
        txtAddressStaff.setRows(5);
        jScrollPane3.setViewportView(txtAddressStaff);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlthisathach/icons/new-icon-16.png"))); // NOI18N
        btnNew.setText("Tạo mới");
        btnNew.setPreferredSize(new java.awt.Dimension(99, 25));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlthisathach/icons/Save-icon.png"))); // NOI18N
        btnUpdate.setText("Cập nhập");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlthisathach/icons/Button-Close-icon-16.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setMaximumSize(new java.awt.Dimension(99, 25));
        btnDelete.setMinimumSize(new java.awt.Dimension(99, 25));
        btnDelete.setPreferredSize(new java.awt.Dimension(99, 25));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên tài khoản", "Mật khẩu", "Họ và tên", "Giới tính", "Email", "Số điện thoại", "Địa chỉ", "Chức vụ"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    tblStaff.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblStaffMouseClicked(evt);
        }
    });
    jScrollPane4.setViewportView(tblStaff);

    jLabel16.setText("Password:");

    jLabel17.setText("Username:");

    cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRATOR", "STAFF" }));
    cbbChucVu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbbChucVuActionPerformed(evt);
        }
    });

    jLabel1.setText("Chức vụ:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 47, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnUpdate)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(130, 130, 130)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel17)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel16))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNameStaff)
                        .addComponent(txtMailStaff)
                        .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addComponent(txtPassword)
                        .addComponent(txtNumberStaff)))
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(rdbMale)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rdbFemale)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbbChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addContainerGap())
        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel16)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(txtNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(txtMailStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(txtNumberStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rdbMale)
                .addComponent(rdbFemale)
                .addComponent(jLabel13)
                .addComponent(btnUpdate))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel14)
                    .addGap(16, 16, 16)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
            .addGap(18, 18, 18)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(47, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        
        UsersDTO userdto=new UsersDTO(); 
        if(txtUsername.getText().equals("") || txtPassword.getText().equals("") || txtNameStaff.getText().equals("") || txtMailStaff.getText().equals("") || txtNumberStaff.getText().equals("") || txtAddressStaff.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Xin vui lòng điền đầy đủ thông tin!");
        
        }else{
            
            userdto.setUsername(txtUsername.getText());
            userdto.setPassword(txtPassword.getText());
            userdto.setFullname(txtNameStaff.getText());
            String sex="";
            if(rdbMale.isSelected()){
                sex = rdbMale.getText();               
            }
            if(rdbFemale.isSelected()){
                sex = rdbFemale.getText();
            }
            userdto.setGioi_tinh(sex);
            userdto.setEmail(txtMailStaff.getText());
            userdto.setSdt(txtNumberStaff.getText());
            userdto.setDia_chi(txtAddressStaff.getText());
            userdto.setChuc_vu(cbbChucVu.getSelectedItem().toString());
            new UsersDAO().addUserDAO(userdto);
            table_update();
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void cbbChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbChucVuActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            
            String username = txtUsername.getText();
            String password = txtPassword.getText();
            String name = txtNameStaff.getText();
            String email = txtMailStaff.getText();
            String phone = txtNumberStaff.getText();
            String sex="";
            if(rdbMale.isSelected()){
                sex = rdbMale.getText();               
            }
            if(rdbFemale.isSelected()){
                sex = rdbFemale.getText();
            }
            String adress = txtAddressStaff.getText();
            String position = cbbChucVu.getSelectedItem().toString();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
            query = conn.prepareStatement("update users set password=?, fullname=?, gioi_tinh=?,email=?, sdt=?, dia_chi=?, chuc_vu=? where username=? ");
            query.setString(1, password);
            query.setString(2, name);
            query.setString(3, sex);
            query.setString(4, email);
            query.setString(5, phone);
            query.setString(6, adress);
            query.setString(7, position);
            query.setString(8, username);
            query.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cập nhập thành công!");
            table_update();
            txtUsername.setText("");
            txtPassword.setText("");
            txtNameStaff.setText("");
            txtMailStaff.setText("");
            txtNumberStaff.setText("");
            txtAddressStaff.setText("");
            clearRadioGroup();
            txtUsername.requestFocus();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStaffMouseClicked
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)tblStaff.getModel();
        int selectedIndex = tblStaff.getSelectedRow();        
        txtUsername.setText(df.getValueAt(selectedIndex, 0).toString());
        txtPassword.setText(df.getValueAt(selectedIndex, 1).toString());
        txtNameStaff.setText(df.getValueAt(selectedIndex, 2).toString());
        if(df.getValueAt(selectedIndex, 3).toString().equals("Nam")){
            rdbMale.setSelected(true);
        }
        if(df.getValueAt(selectedIndex, 3).toString().equals("Nữ")){
            rdbFemale.setSelected(true);
        }
        txtMailStaff.setText(df.getValueAt(selectedIndex, 4).toString());
        txtNumberStaff.setText(df.getValueAt(selectedIndex, 5).toString());
        txtAddressStaff.setText(df.getValueAt(selectedIndex, 6).toString());
        cbbChucVu.setSelectedItem(df.getValueAt(selectedIndex, 7));
    }//GEN-LAST:event_tblStaffMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)tblStaff.getModel();
        int selectedIndex = tblStaff.getSelectedRow();
        try{
            String username = txtUsername.getText();
            int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa thông tin này?", "Warning", JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
                query = conn.prepareStatement("DELETE FROM users WHERE username=? ");
                query.setString(1,username);
                query.executeUpdate();
                JOptionPane.showMessageDialog(this, "Đã xóa!");
                table_update();
                txtUsername.setText("");
                txtPassword.setText("");
                txtNameStaff.setText("");
                txtMailStaff.setText("");
                txtNumberStaff.setText("");
                txtAddressStaff.setText("");
                clearRadioGroup();
                txtUsername.requestFocus();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        } 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void rdbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMaleActionPerformed
    private void clearRadioGroup() {
        buttonGroup1.clearSelection();
    }
    PreparedStatement query;
    private void table_update(){
        int c;
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
                query = conn.prepareStatement("SELECT * FROM users");
                ResultSet rs = query.executeQuery();
                ResultSetMetaData rss = rs.getMetaData();
                c = rss.getColumnCount();
                
                DefaultTableModel df = (DefaultTableModel)tblStaff.getModel();
                df.setRowCount(0);
                    while(rs.next()){
                        Vector v2 = new Vector();
                        for (int a = 1; a <=c; a++) {
                            v2.add(rs.getString("username"));
                            v2.add(rs.getString("password"));
                            v2.add(rs.getString("fullname"));
                            v2.add(rs.getString("gioi_tinh"));
                            v2.add(rs.getString("email"));
                            v2.add(rs.getString("sdt"));                   
                            v2.add(rs.getString("dia_chi"));
                            v2.add(rs.getString("chuc_vu"));
                        }
                        df.addRow(v2);
                    }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rdbFemale;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextArea txtAddressStaff;
    private javax.swing.JTextField txtMailStaff;
    private javax.swing.JTextField txtNameStaff;
    private javax.swing.JTextField txtNumberStaff;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
