/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlthisathach;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mysql_DAO.SinhvienDAO;
import mysql_DTO.SinhvienDTO;
import static qlthisathach.MainFormAdmin.user_id;
import static qlthisathach.MainFormNV.userNV_id;


/**
 *
 * @author MSI
 */
public class StudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThemThiSinh
     */
    public StudentPanel() {
        initComponents();
        FillcomboLbl();
        table_update();
        
    }
PreparedStatement query;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdbFemale = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddressTS = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txtNameTS = new javax.swing.JTextField();
        txtMailTS = new javax.swing.JTextField();
        txtNumberTS = new javax.swing.JTextField();
        rdbMale = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblThiSinh = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtQueQuanTS = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbbLbl = new javax.swing.JComboBox<>();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtCmnd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        buttonGroup1.add(rdbFemale);
        rdbFemale.setText("Nữ");

        jLabel10.setText("Họ tên:");

        jLabel11.setText("Email:");

        jLabel12.setText("Số điện thoại:");

        jLabel13.setText("Giới tính:");

        txtAddressTS.setColumns(20);
        txtAddressTS.setRows(5);
        jScrollPane3.setViewportView(txtAddressTS);

        jLabel14.setText("Địa chỉ:");

        buttonGroup1.add(rdbMale);
        rdbMale.setText("Nam");

        tblThiSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ và tên", "Loại bằng lái", "Ngày sinh", "Giới tính", "Email", "Số điện thoại", "Địa chỉ", "Quê quán", "Chứng minh nhân dân"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    tblThiSinh.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblThiSinhMouseClicked(evt);
        }
    });
    jScrollPane4.setViewportView(tblThiSinh);

    jLabel16.setText("Ngày sinh:");

    jLabel17.setText("Quê quán:");

    jLabel18.setText("Loại bằng lái:");

    btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlthisathach/icons/new-icon-16.png"))); // NOI18N
    btnNew.setText("Tạo mới");
    btnNew.setPreferredSize(new java.awt.Dimension(99, 25));
    btnNew.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnNewActionPerformed(evt);
        }
    });

    btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlthisathach/icons/Save-icon.png"))); // NOI18N
    btnUpdate.setText("Cập nhập");
    btnUpdate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnUpdateActionPerformed(evt);
        }
    });

    btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlthisathach/icons/Button-Close-icon-16.png"))); // NOI18N
    btnDelete.setText("Xóa");
    btnDelete.setMaximumSize(new java.awt.Dimension(99, 25));
    btnDelete.setMinimumSize(new java.awt.Dimension(99, 25));
    btnDelete.setPreferredSize(new java.awt.Dimension(99, 25));
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnDeleteActionPerformed(evt);
        }
    });

    jLabel19.setText("CMND:");

    jLabel1.setText("ID:");

    txtID.setEditable(false);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jSeparator2)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(123, 123, 123)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                        .addComponent(cbbLbl, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtQueQuanTS)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdbMale)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rdbFemale)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(txtCmnd)))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMailTS, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNumberTS)
                                        .addComponent(txtNameTS)))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtID)))))))
            .addContainerGap())
        .addComponent(jScrollPane4)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNameTS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtMailTS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(txtNumberTS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(rdbMale)
                        .addComponent(rdbFemale)))
                .addGroup(layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(btnUpdate)
                    .addGap(49, 49, 49)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQueQuanTS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(cbbLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    private void FillcomboLbl(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
            query = conn.prepareStatement("SELECT * FROM loaibanglai");
            rs=query.executeQuery();
            while(rs.next()){
                String name = rs.getString("ten_loai_bang_lai");
                cbbLbl.addItem(name);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public void clear_text(){
        txtID.setText("");
        txtNameTS.setText("");
        txtMailTS.setText("");
        txtNumberTS.setText("");
        buttonGroup1.clearSelection();
        txtAddressTS.setText("");     
        txtQueQuanTS.setText("");
        txtCmnd.setText("");
    }
    
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        SinhvienDTO svdto=new SinhvienDTO(); 
        if(txtNameTS.getText().equals("") || txtMailTS.getText().equals("") || txtCmnd.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Xin vui lòng điền đầy đủ thông tin!");
        }else{   
            svdto.setFullname(txtNameTS.getText());
            java.util.Date utilStartDate = jDateChooser1.getDate();
            java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
            svdto.setNgay_sinh(sqlStartDate);
            String sex="";
            if(rdbMale.isSelected()){
                sex = rdbMale.getText();               
            }
            if(rdbFemale.isSelected()){
                sex = rdbFemale.getText();
            }
            svdto.setGioi_tinh(sex);
            svdto.setEmail(txtMailTS.getText());
            svdto.setSdt(txtNumberTS.getText());
            svdto.setDia_chi(txtAddressTS.getText());
            svdto.setQue_quan(txtQueQuanTS.getText());
            svdto.setCmnd(txtCmnd.getText()); 
            Integer A1 = 1;
            Integer A2 = 2;
            Integer A3 = 3;
            Integer A4 = 4;
            Integer B1 = 5;
            Integer B2 = 6;
            Integer C = 7;
            Integer D = 8;
            Integer E = 9;
            Integer F = 10;
            Integer FB2 = 11;
            Integer FC = 12;
            Integer FD = 13;
            Integer FE = 14;
            Integer diem = 0;
            Object selectedItem = cbbLbl.getSelectedItem();
            String selectedItemStr = selectedItem.toString();
            if (selectedItemStr.equals("Hạng A1")) {
                svdto.setLbl_id(A1);
            }
            if (selectedItemStr.equals("Hạng A2")) {
                svdto.setLbl_id(A2);
            }
            if (selectedItemStr.equals("Hạng A3")) {
                svdto.setLbl_id(A3);
            }
            if (selectedItemStr.equals("Hạng A4")) {
                svdto.setLbl_id(A4);
            }
            if (selectedItemStr.equals("Hạng B1")) {
                svdto.setLbl_id(B1);
            }
            if (selectedItemStr.equals("Hạng B2")) {
                svdto.setLbl_id(B2);
            }
            if (selectedItemStr.equals("Hạng C")) {
                svdto.setLbl_id(C);
            }
            if (selectedItemStr.equals("Hạng D")) {
                svdto.setLbl_id(D);
            }
            if (selectedItemStr.equals("Hạng E")) {
                svdto.setLbl_id(E);
            }
            if (selectedItemStr.equals("Hạng F")) {
                svdto.setLbl_id(F);
            }
            if (selectedItemStr.equals("Hạng FB2")) {
                svdto.setLbl_id(FB2);
            }
            if (selectedItemStr.equals("Hạng FC")) {
                svdto.setLbl_id(FC);
            }
            if (selectedItemStr.equals("Hạng FD")) {
                svdto.setLbl_id(FD);
            }
            if (selectedItemStr.equals("Hạng FE")) {
                svdto.setLbl_id(FE);
            }
            svdto.setUsers_id(user_id.getText());
            svdto.setDiem(diem);
            new SinhvienDAO().addSVDAO(svdto);
            table_update();
            clear_text();
        }
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            java.util.Date utilStartDate = jDateChooser1.getDate();
            java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
            String fullname = txtNameTS.getText();
            String email = txtMailTS.getText();
            String sdt = txtNumberTS.getText();
            String dia_chi = txtAddressTS.getText();
            
            String sex="";
            if(rdbMale.isSelected()){
                sex = rdbMale.getText();               
            }
            if(rdbFemale.isSelected()){
                sex = rdbFemale.getText();
            }
            String que_quan = txtQueQuanTS.getText();
            Integer lbl = null;
            Integer A1 = 1;
            Integer A2 = 2;
            Integer A3 = 3;
            Integer A4 = 4;
            Integer B1 = 5;
            Integer B2 = 6;
            Integer C = 7;
            Integer D = 8;
            Integer E = 9;
            Integer F = 10;
            Integer FB2 = 11;
            Integer FC = 12;
            Integer FD = 13;
            Integer FE = 14;
            Object selectedItem = cbbLbl.getSelectedItem();
            String selectedItemStr = selectedItem.toString();
            if (selectedItemStr.equals("Hạng A1")) {
                lbl = A1;
            }
            if (selectedItemStr.equals("Hạng A2")) {
                lbl = A2;
            }
            if (selectedItemStr.equals("Hạng A3")) {
                lbl = A3;
            }
            if (selectedItemStr.equals("Hạng A4")) {
                lbl = A4;
            }
            if (selectedItemStr.equals("Hạng B1")) {
                lbl = B1;
            }
            if (selectedItemStr.equals("Hạng B2")) {
                lbl = B2;
            }
            if (selectedItemStr.equals("Hạng C")) {
                lbl = C;
            }
            if (selectedItemStr.equals("Hạng D")) {
                lbl = D;
            }
            if (selectedItemStr.equals("Hạng E")) {
                lbl = E;
            }
            if (selectedItemStr.equals("Hạng F")) {
                lbl = F;
            }
            if (selectedItemStr.equals("Hạng FB2")) {
                lbl = FB2;
            }
            if (selectedItemStr.equals("Hạng FC")) {
                lbl = FC;
            }
            if (selectedItemStr.equals("Hạng FD")) {
                lbl = FD;
            }
            if (selectedItemStr.equals("Hạng FE")) {
                lbl = FE;
            }
            String cmnd = txtCmnd.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
            query = conn.prepareStatement("update sinhvien set fullname=?, ngay_sinh=?, gioi_tinh=?,email=?, sdt=?, dia_chi=?, que_quan=?, lbl_id=? where cmnd=? ");
            query.setString(1, fullname);
            query.setDate(2, sqlStartDate);
            query.setString(3, sex);
            query.setString(4, email);
            query.setString(5, sdt);
            query.setString(6, dia_chi);
            query.setString(7, que_quan);
            query.setInt(8, lbl);
            query.setString(9, cmnd);
            query.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cập nhập thành công!");
            table_update();
            clear_text();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String id = txtID.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
            query = conn.prepareStatement("delete from sinhvien where sinh_vien_id=?");
            query.setString(1, id);
            query.executeUpdate();
            JOptionPane.showMessageDialog(this, "Đã xóa!");
            table_update();
            clear_text();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblThiSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThiSinhMouseClicked
        DefaultTableModel df = (DefaultTableModel)tblThiSinh.getModel();
        int selectedIndex = tblThiSinh.getSelectedRow();   
        txtID.setText(df.getValueAt(selectedIndex, 0).toString());
        txtNameTS.setText(df.getValueAt(selectedIndex, 1).toString());
        txtMailTS.setText(df.getValueAt(selectedIndex, 5).toString());
        txtNumberTS.setText(df.getValueAt(selectedIndex, 6).toString());
        if(df.getValueAt(selectedIndex, 4).toString().equals("Nam")){
            rdbMale.setSelected(true);
        }
        if(df.getValueAt(selectedIndex, 4).toString().equals("Nữ")){
            rdbFemale.setSelected(true);
        }
        Date date;
        try{
            date = new SimpleDateFormat("yyyy-MM-dd").parse((String)df.getValueAt(selectedIndex, 3));
            jDateChooser1.setDate(date);
        } catch (ParseException ex){
            Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtAddressTS.setText(df.getValueAt(selectedIndex, 7).toString());
        txtQueQuanTS.setText(df.getValueAt(selectedIndex, 8).toString());
        txtCmnd.setText(df.getValueAt(selectedIndex, 9).toString());
        cbbLbl.setSelectedItem(df.getValueAt(selectedIndex, 2));
    }//GEN-LAST:event_tblThiSinhMouseClicked
    private void table_update(){
        int c;
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_javaproject", "root", "09022000");
                query = conn.prepareStatement("select sinhvien.sinh_vien_id, "
                        + "sinhvien.fullname, loaibanglai.ten_loai_bang_lai, "
                        + "sinhvien.ngay_sinh, sinhvien.gioi_tinh, sinhvien.email, "
                        + "sinhvien.sdt, sinhvien.dia_chi, sinhvien.que_quan, "
                        + "sinhvien.cmnd, sinhvien.diem\n" +
                        "from sinhvien\n" +
                        "left join loaibanglai on sinhvien.lbl_id = loaibanglai.lbl_id;");
                ResultSet rs = query.executeQuery();
                ResultSetMetaData rss = rs.getMetaData();
                c = rss.getColumnCount();
                
                DefaultTableModel df = (DefaultTableModel)tblThiSinh.getModel();
                df.setRowCount(0);
                    while(rs.next()){
                        Vector v2 = new Vector();
                        for (int a = 1; a <=c; a++) {
                            v2.add(rs.getString("sinh_vien_id")); //0
                            v2.add(rs.getString("fullname")); //1
                            v2.add(rs.getString("ten_loai_bang_lai"));//2
                            v2.add(rs.getString("ngay_sinh"));//3
                            v2.add(rs.getString("gioi_tinh"));//4
                            v2.add(rs.getString("email"));//5         
                            v2.add(rs.getString("sdt"));//6
                            v2.add(rs.getString("dia_chi"));//7
                            v2.add(rs.getString("que_quan"));//8
                            v2.add(rs.getString("cmnd"));//9
                            v2.add(rs.getString("diem"));
                        }
                        df.addRow(v2);
                    }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbLbl;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rdbFemale;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JTable tblThiSinh;
    private javax.swing.JTextArea txtAddressTS;
    private javax.swing.JTextField txtCmnd;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMailTS;
    private javax.swing.JTextField txtNameTS;
    private javax.swing.JTextField txtNumberTS;
    private javax.swing.JTextField txtQueQuanTS;
    // End of variables declaration//GEN-END:variables
}
